ln -sf $(pwd)/home/.config/nvim/init.vim ~/.config/nvim/init.vim
ln -sf $(pwd)/home/.config/nvim/plugins.vim ~/.config/nvim/plugins.vim
ln -sf $(pwd)/home/.config/nvim/settings.vim ~/.config/nvim/settings.vim
ln -sf $(pwd)/home/.config/nvim/auto-completion.vim ~/.config/nvim/auto-completion.vim
ln -sf $(pwd)/home/.config/nvim/lsp.vim ~/.config/nvim/lsp.vim
ln -sf $(pwd)/home/.config/nvim/search.vim ~/.config/nvim/search.vim
ln -sf $(pwd)/home/.zshrc ~/.zshrc
ln -sf $(pwd)/home/.ghci ~/.ghci
ln -sf $(pwd)/home/.gitconfig ~/.gitconfig
